"""Database tables. Schema changes go through Alembic (../alembic)."""

import enum
import uuid
from datetime import datetime

from sqlalchemy import CheckConstraint, DateTime, Enum, ForeignKey, String, UniqueConstraint, func
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db import Base


class User(Base):
    __tablename__ = "users"

    id: Mapped[int] = mapped_column(primary_key=True)
    username: Mapped[str] = mapped_column(String(32), unique=True, index=True)
    password_hash: Mapped[str] = mapped_column(String(255))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))


class FriendshipStatus(str, enum.Enum):
    pending = "pending"
    accepted = "accepted"
    declined = "declined"


class Friendship(Base):
    """One row per pair of users, whoever asked first.

    The pair is stored in a fixed order (user_low_id < user_high_id), so
    "alice → bob" and "bob → alice" can never become two separate rows.
    """

    __tablename__ = "friendships"
    __table_args__ = (
        UniqueConstraint("user_low_id", "user_high_id", name="uq_friendships_pair"),
        CheckConstraint("user_low_id < user_high_id", name="ck_friendships_ordered_pair"),
    )

    id: Mapped[int] = mapped_column(primary_key=True)
    user_low_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), index=True)
    user_high_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), index=True)
    requested_by_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"))
    status: Mapped[FriendshipStatus] = mapped_column(
        Enum(FriendshipStatus, name="friendship_status"), default=FriendshipStatus.pending
    )
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(), onupdate=func.now()
    )

    user_low: Mapped[User] = relationship(foreign_keys=[user_low_id])
    user_high: Mapped[User] = relationship(foreign_keys=[user_high_id])

    def other_user(self, me_id: int) -> User:
        return self.user_high if self.user_low_id == me_id else self.user_low


class CallStatus(str, enum.Enum):
    ringing = "ringing"
    accepted = "accepted"  # callee picked up, WebRTC negotiation running / media flowing
    ended = "ended"  # was accepted, then someone hung up
    declined = "declined"  # callee said no
    missed = "missed"  # nobody answered before the ring timeout
    cancelled = "cancelled"  # caller gave up while ringing
    failed = "failed"  # e.g. a peer disconnected


class Call(Base):
    """Call history. Written by the signal server through /internal endpoints."""

    __tablename__ = "calls"

    id: Mapped[uuid.UUID] = mapped_column(primary_key=True)  # generated by the signal server
    caller_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), index=True)
    callee_id: Mapped[int] = mapped_column(ForeignKey("users.id", ondelete="CASCADE"), index=True)
    media: Mapped[str] = mapped_column(String(8))  # "audio" | "video"
    status: Mapped[CallStatus] = mapped_column(Enum(CallStatus, name="call_status"))
    end_reason: Mapped[str | None] = mapped_column(String(64))
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now())
    answered_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    ended_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    caller: Mapped[User] = relationship(foreign_keys=[caller_id])
    callee: Mapped[User] = relationship(foreign_keys=[callee_id])
